name: Flutter CI + Firebase Distribution

on:
  push:
    branches: [ "main", "feature/offiline" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      # 3. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      - name: Set version
        run: |
          VERSION_NAME=$(grep '^version:' pubspec.yaml | cut -d '+' -f 1 | sed 's/version: //')
          BUILD_NUMBER=${{ github.run_number }}
          sed -i "s/^version: .*/version: $VERSION_NAME+$BUILD_NUMBER/" pubspec.yaml

      # 4. Testes (opcional mas recomendado)
      - name: Run tests
        run: flutter test || true

      # 5. Restore keystore & signing config
      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode >
          android/upload-keystore.jks

      - name: Create key.properties
        run: |
          cat > android/key.properties << EOF
          storePassword=${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          storeFile=../upload-keystore.jks
          EOF

      # 6. Build APK
      - name: Build APK
        run: flutter build apk --release --dart-define=FLAVOR=prod

      # 7. Upload Firebase
      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          groups: beta
          file: build/app/outputs/flutter-apk/app-release.apk
